### ISSUE TITLE
Documentation for complete API

### ISSUE THREAD

**Issue by renestalder** [hotwired/stimulus#372]
I took a look at the source code and found that there might be more "features" than are visible in the current documentation on the website. I wondered if this information is omitted accidentally or willingly. For example, functions like `getControllerForElementAndIdentifier` on the application object which can be quite handy if one knows that it exists.

Any plans to extend the documentation for a full reference of all available functions?

Also, side-note, it would be nice if the functions featured JSDoc comments so that the reference for IDEs and code editors supporting JSDoc can show this additional information. ~~Or at least the generated `d.ts` files would already be an improvement.~~

**Comment by evromalarkey** [comment]
I second this, there is not much documentation on how to communicate between controllers. I am also wondering if there is function to add controller to DOM via javascript with promise or callback. 

Eg. if I want to load controller from another controller, I can do it only with `setAttribute("data-controller")`. That's not much effective, because I don't know when the controller is connected so I need to add setTimeout before I can communicate with it. So is there something like `connectController` which returns promise?

Btw `getControllerForElementAndIdentifier` is really long, can't it be shorten to getController?

Some basic API for communication between controllers would be nice (if there isn't already) - `connectController`, `disconnectController`, `getController` etc.

**Comment by lordcysiek** [comment]
Bump up! I'm Stimulus newcomer and I'm more then confused. Having more detailed API doc would be great option.

I was reading:https://www.betterstimulus.com/interaction/controller-dom-mapper.html
plus most resources i found in via google. Most examples refers to:
`this.element[this.identifier] = this;` which does not work for my scenario where i have separated controllers, not connected to the same DOMElement.
binding via `this.application.element[this.identifier] = this;` solves the issue, but raises the question - **is this the right way**?

I can go YOLO style and bind this way ;]:
`this.application[this.identifier] = this;`

Is there any reason i shouldn't keep my controllers separated from DOMElement?

**Comment by leastbad** [comment]
Hey gang, it's true that there's a lot of "missing manual" around Stimulus.

The best way to learn advanced Stimulus techniques IMHO is to read the source of projects like [stimulus-use](https://stimulus-use.github.io/stimulus-use/) and [StimulusReflex](https://docs.stimulusreflex.com). The [SR client](https://github.com/hopsoft/stimulus_reflex/blob/master/javascript/stimulus_reflex.js) is likely the most sophisticated Stimulus controller, today.

@julianrubisch has done a heroic job of compiling a lot of the missing concepts on https://betterstimulus.com (as linked by @lordcysiek above) but there's always more and we're still discovering new patterns all of the time.

New patterns is my segue to the issue of controller-to-controller communication! When I proposed the `this.element['foo'] = this` binding technique, I didn't intend that it was for controllers that are connected to the same DOM element, *at all*.

You can talk across `this.element`, but the goal is to access controllers on elements elsewhere in the DOM that you have a reference to, usually via `id` query. You might have a `<div id="content" data-controller="content"></div>` that is conceptually important in your application; you also have components anywhere on the page that need to access the internal state of the `content` controller instance. This is an intentional set of design decisions which allow you to build-up functionality.

Raising and listening for custom events should be the first tool you reach for when you need to communicate between Stimulus controllers. One of the "missing manual" concepts is how most of what people put in their `connect` should actually be in `initialize`, leaving `connect` and `disconnect` almost exclusively to set up `addEventListener`/`removeEventListener` pairs.

However, event dispatch is passive and asyncronous; you're working in callbacks. There are times where you need to reach into a controller and access its internal state - whether to inspect a variable or execute a method - from your current scope **right now**... and that's what hanging `this` on a variable on an element is for.

**Comment by asadakbar** [comment]
@leastbad great feedback. I think your comment would be very helpful to others as a post on your blog.

Also, can you expand a bit on your point about initialize versus connect? I find myself doing what you mentioned many developers do, so would love to know more about the difference between the two lifecycle functions and what you would put in each.

**Comment by asadakbar** [comment]
@evromalarkey I have seen @sstephenson mention in other places that getControllerForElementAndIdentifier was intentionally made to be long to discourage its use. 

He stated that their stance on communicating between controllers is that one should be nested within another and the nested controller would emit an event that is handled by the outer controller as the event bubbles up. 

Although it has been some time since I saw that so the stimulus team may have evolved their thinking on this.

**Comment by leastbad** [comment]
> @leastbad great feedback. I think your comment would be very helpful to others as a post on your blog.

You're in luck! https://leastbad.com/stimulus-power-move
 
> Also, can you expand a bit on your point about initialize versus connect? I find myself doing what you mentioned many developers do, so would love to know more about the difference between the two lifecycle functions and what you would put in each.

Keep in mind that every developer's experience is going to be subjective and informed on what tools they've used in the past. I came from a jQuery background and it really took me a while to get my head around the idea that every time you assign a controller, that's an independent instance of a class. There are often things you might want to do to set up the internal state of that instance, whether it's initializing 3rd-party libraries, obtaining references to DOM elements or in some cases even removing the controller from the element if conditions aren't meant! The key is that this is all stuff you do exactly once, and it has nothing to do with the element being added to the DOM. That's your `initialize` method.

`connect` and `disconnect` are the thing jQuery developers need to unlearn to thrive with Stimulus. That is, it's the evolution from thinking in terms of a one-time page load event orgy to a model where a DOM element might be loaded on the initial page load, cached by Turbolinks, restored by the back button, added dynamically by an Ajax request, added dynamically by [StimulusReflex](https://docs.stimulusreflex.com)... that means `connect` and `disconnect` is stuff you want to happen when the element is added and later, removed. For me, this is 90% of the time `this.element.addEventListener()` type calls, because you don't want to leave event handlers when an element isn't even in your DOM. I tend to handle events directly in this manner, and leave the Stimulus `data-action` attributes for controllers I plan to distribute via npm, as a sort of developer API.

> Finally, regarding turning to raising and catching events across controllers, I feel like there is a dearth of examples for how best to do that. Especially for scenarios where one controller is not nested within another. If you could make a post about that I would love to read it.

I understand that this must be frustrating! I actually suspect that the best thing is to keep reading code and seeing how others use events to talk between controllers. I go into a bit more detail in the CableReady docs but fair warning, while CR is amazing and you should use it, it's not a 1:1 answer to your request. https://cableready.stimulusreflex.com/leveraging-stimulus

**Comment by dhh** [comment]
Feel free to turn any of these discussions into doc PRs for consideration.
