### ISSUE TITLE
Cannot resolve symbol "Controller"

### ISSUE THREAD

**Issue by adpeyre** [hotwired/stimulus#384]
Hi,

I've a problem. PHPStorm can't resolve import.

![image](https://user-images.githubusercontent.com/12408697/110505057-18241b00-80fe-11eb-95a9-d880d8b5261f.png)

Can you help me ?

Thx

**Comment by Sub-Xaero** [comment]
Same here with Rubymine, always been like that for me. 

My thesis is that Jetbrains IDEs can't find the actual type definition for `Controller` because Stimulus just does `export * from "@stimulus/core"`, and the IDE can't follow the indirection to find the actual `controller.d.ts` in the `@stimulus/core` library.

Obviously not perfect for IntelliSense, but your bundler should still compile it just fine.

**Comment by adpeyre** [comment]
Thanks @Sub-Xaero 
It works but it's a shame not to be able to take advantage of autocompletion.

**Comment by adpeyre** [comment]
I've just asked to PHPStorm on Twitter.
https://twitter.com/adpeyre/status/1369363485239435267

**Comment by adpeyre** [comment]
Sorry, it's not an issue. Just my node_modules folder which was excluded in PHPStorm....

**Comment by DerDu** [comment]
Could this be part of installation documentation?
