### ISSUE TITLE
TypeError: setting getter-only property "observeTarget"

### ISSUE THREAD

**Issue by robbevp** [hotwired/stimulus#393]
Hi there 👋 

I'm trying to upgrade `@rails/webpacker` to the webpacker 6 beta (mostly so I can use postcss 8), but am getting a errors that stem from stimulus.

My stimulus controllers have obviously not changed, but I'm now getting the following errors in my console:
```js
Uncaught (in promise) TypeError: setting getter-only property "observeTarget"
    _class reveal_controller.ts:3
    extended blessing.js:77
    Context context.js:7

```

If I remove or rename the target (for example, by renaming `targets = ["observe"]` to `targets = ["observed"]`, the error disappears but another target throws the same error. The stack trace always starts with the line that creates the controller.

Once I resolved the errors for targets on the page I'm loading, the class methods throw a similar error:
```js
Uncaught (in promise) TypeError: setting getter-only property "hasHideClass"
    _class show_controller.ts:3
    extended blessing.js:77
    Context context.js:7
```

Any suggestions/help on what could be the problem here? I'm not sure if this is a problem with my config on my end or within stimulus.

For clarity:
I write my stimulus controllers in typescript. I use webpacker 6 and the typescript with pretty much all default options as laid out in the [docs](https://github.com/rails/webpacker#typescript). The only difference being the my `tsconfig.json` has es6 as a target.

I get this error in FF 87 and Chrome 89 (though the error is written as `Uncaught TypeError: Cannot set property hasHideClass of #<extended> which has only a getter`

**Comment by rreinhardt9** [comment]
Hi @robbevp ! In case this helps and you are still running into this, I was running into the exact same issue. For me, it turned out that my `package.json` presets had been changed when I re-ran `rake webpacker:install` to try and solve another issue. I had previously added a preset for typescript which was removed when I re-ran that rake task. Here is what it should have looked like for me:

```JSON
  "babel": {
    "presets": [
      [
        "./node_modules/@rails/webpacker/package/babel/preset.js"
      ],
      [
        "@babel/preset-typescript"
      ]
    ]
  },
```

but instead it had become:
```JSON
    "presets": [
      "./node_modules/@rails/webpacker/package/babel/preset.js"
    ]
```

Once I added the "@babel/preset-typescript" preset again I no longer saw the `Uncaught TypeError: Cannot set property` errors; so it seemed to be a typescript/ babel configuration error in that case.

I had a target that looked like:

```TS
  static targets = ['formField']
  formFieldTarget: HTMLInputElement
```

and trying to load that controller on the page began to give me the error: `Uncaught (in promise) TypeError: setting getter-only property "formFieldTarget"`.

**Comment by robbevp** [comment]
hi @rreinhardt9,
I was able to solve this in a similar way. Since I also want some other features that are not default in `@babel/preset-typescript` I overwrite the preset from webpacker as follows:
```json
"babel": {
    "presets": [
      "./node_modules/@rails/webpacker/package/babel/preset.js",
      [
        "@babel/preset-typescript",
        {
          "allExtensions": true,
          "isTSX": true,
          "allowDeclareFields": true
        }
      ]
    ]
  },
  ```
