### ISSUE TITLE
Controller scopes

### ISSUE THREAD

**Issue by gahia** [hotwired/stimulus#403]
Having two NOT NESTED elements using the same controller, like here:

```
<div data-controller="file-preview">...</div>
<div data-controller="file-preview">...</div>
```
I understand, there should be two exclusive scopes then both elements should work independently.  But when executing an action on the second element, it's using the targets assigned in the first element instead.

Here the code to try it: https://codepen.io/gahia/pen/BaWjgWG

**Comment by Sub-Xaero** [comment]
Your problem is that you have 2 inputs and 2 labels with the same name/id. 

When you click on the second `<label for="avatar">`, the browser is triggering the dialog for the first file input. 

If you give them different names, everything works as expected: https://codepen.io/SubXaero/pen/bGqEPmP?editors=1111

**Comment by gahia** [comment]
You're right! Was there all the time!

Thanks so much 🙌
