### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by vastray** [hotwired/stimulus#489]
Removed elements are not deleted from memory.

![Снимок экрана от 2021-11-12 13-47-05](https://user-images.githubusercontent.com/51928487/141451228-794e626c-b00e-4512-b4f1-04821bc5e729.png)
^^^ Nodes and Listeners are not cleared

We create the "List" controller, in it we create elements for the "Item" controller. When the button is clicked, the item is cleared and a list is created. When you click on the "Reload" button, a memory leak occurs. The garbage collector doesn't help.

Example:

index.html
```html
<div data-controller="list">
    <button data-action="list#reload">Reload</button>
    <div data-list-target="listContainer"></div>
</div>
```

script.js
```javascript
const data = ['name1', 'name2', 'name3', 'name4', 'name5', 'name6', 'name7', 'name8']

Stimulus.register("list", class extends Controller {

    static targets = ['listContainer']

    connect() {
        this.load()
    }

    load() {
        data.forEach((name) => {
            const div = document.createElement('div')
            div.setAttribute('data-controller', 'item')
            div.setAttribute('data-action', 'click->item#log')
            div.innerText = name
            this.listContainerTarget.appendChild(div)
        })
    }

    reload() {
        this.listContainerTarget.innerHTML = ''
        this.load()
    }
})

Stimulus.register("item", class extends Controller {

    log() {
        console.log('click')
    }

})
```

**Comment by tleish** [comment]
I'm pretty sure this has nothing to do with stimulus.  In this instance, stimulus is the event handling for executing the javascript, it the standard javascript that creating and clearing the nodes.

It's been discussed a lot in other javascript forums: 
- [javascript - Empty-ing innerHTML increases number of DOM nodes - Stack Overflow](https://stackoverflow.com/questions/22486030/empty-ing-innerhtml-increases-number-of-dom-nodes)
- [javascript - How to remove DOM elements without memory leaks? - Stack Overflow](https://stackoverflow.com/questions/3785258/how-to-remove-dom-elements-without-memory-leaks)
- [Deleting HTML Elements in JavaScript to avoid memory leaks - Stack Overflow](https://stackoverflow.com/questions/49147182/deleting-html-elements-in-javascript-to-avoid-memory-leaks)

If it's not an issue, you can ignore it.  Otherwise for you can read through this post for possible alternatives to innerHTML:
- [Remove all child elements of a DOM node in JavaScript - Stack Overflow](https://stackoverflow.com/questions/3955229/remove-all-child-elements-of-a-dom-node-in-javascript)

**Comment by vastray** [comment]
@tleish I noticed an interesting feature. If I remove the line:
```javascript
div.setAttribute('data-action', 'click->item#log')
```
Nodes are removed as expected. I don't understand how to explain it.

**Comment by intrip** [comment]
@vastray https://github.com/hotwired/stimulus/pull/592 might have fixed this, can you still reproduce using the latest StimulusJS version?

**Comment by vastray** [comment]
@intrip  Yes, this fixes the current bug. The garbage collector removes all unused nodes. Good job.

![Снимок экрана от 2022-11-01 14-46-34](https://user-images.githubusercontent.com/51928487/199217194-6f11be08-b09b-4c06-a384-01a4872da0a4.png)

**Comment by intrip** [comment]
Great! Let's close the issue now ?
