### ISSUE TITLE
How to get all defined values object inside controller connect()?

### ISSUE THREAD

**Issue by gremo** [hotwired/stimulus#501]
I usually use Stimulus controllers to "boostrap" JavaScript plugins. Most of the time, these plugins accept a lot of options and I need to "map" **plugin options** to **[Stimulus values](https://stimulus.hotwired.dev/reference/values)**. 

This is so boring 😄:

```js
connect() {
  let options = {};
  if (this.hasPathValue) {
    options = { ...options, path: this.pathValue };
  }
  // ... and so on, for each value

  this.plugin = new MyPlugin(this.element, options);
}
```
I end up defining an `options` property (using `this.has[Name]Value` and `this.[name]Value`) over and over:

```js
get options() {
  return Object.keys(this.constructor.values)
    .filter(k => this[`has${k.charAt(0).toUpperCase() + k.slice(1)}Value`])
    .reduce((prev, curr) => ({
      ...prev,
      [curr]: this[`${curr}Value`]
    }), {});
}
```

 Is there any native method in Stimulus to get an object of defined options?

Another option would be a hook-style utility like:

```js
export const useOptions = (controller, defaultOptions = {}) => {
  Object.defineProperty(controller, 'defaultOptions', {
    enumerable: true,
    get: () => defaultOptions,
  });

  Object.defineProperty(controller, 'options', {
    enumerable: true,
    get: () => ({
      ...controller.defaultOptions,
      ...Object.keys(controller.constructor.values ?? {})
        .filter(k => controller[`has${k.charAt(0).toUpperCase() + k.slice(1)}Value`])
        .reduce((prev, curr) => ({
          ...prev,
          [curr]: controller[`${curr}Value`]
        }), {}),
    }),
  });
};

```

**Comment by seanpdoyle** [comment]
I've scanned the [Controller](https://github.com/hotwired/stimulus/blob/v3.0.1/src/core/controller.ts) and [Context](https://github.com/hotwired/stimulus/blob/v3.0.1/src/core/context.ts) classes, and nothing immediately jumps out as a viable interface.

Have you considered passing options as [`Object` values](https://stimulus.hotwired.dev/reference/values#types) instead of individual keys?

If you're stuck with your bespoke approach, you might be able to iterate over the [`this.element.dataset](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dataset) property, checking for keys that begin with `this.identifiter`:

```js
for (const [ key, value ] of this.element.dataset) {
  if (key.startsWith(this.identifier)) {
    // ...
  }
}
```

**Comment by gremo** [comment]
Thank you @seanpdoyle , I've updated the question for a more "easy" way (an "hook"), but still trying to find a native approach (that is something built-in with Stimulus).

Cheers
