### ISSUE TITLE
Alternative syntax for data-action

### ISSUE THREAD

**Issue by phuongnd08** [hotwired/stimulus#513]
I find this syntax to be hard to read and write:
```
<div data-action="timeupdate->move-editor#frameUpdated loadeddata->move-editor#videoLoaded">
```
would suggest something like this:

```
<div 
  data-action-timeupdate="move_editor.frameUpdated()"
  data-action-loadeddata="move_editor.videoLoaded()">
```

This also make params passing pretty straight forward:

```
<div 
  data-action-timeupdate="move_editor.frameUpdated(event, { id: 1 })"
  data-action-loadeddata="move_editor.videoLoaded(event, { id: 2 })">
```

**Comment by lb-** [comment]
The say Stimulus works under the hood is with DOMutationObserver, to ensure that actions can be correctly updated, removed or added dynamically there needs to be a way for the observer to know in advance what attributes it should be aware of. 

This needs to be done as a list of full attribute string names, not just 'attribute starts with data-action'.

Otherwise the performance will degrade as Stimulus now needs to make an observer for every single attribute. 

This is why targets need to be registered on the class, so that the observer can register a known set of attributes to be away of. 

If this syntax were to be adopted, all possible event names that may be used by the controller would need to be declared up front. Otherwise it will mean sacrificing the ability to dynamically add these attributes after the initial page load. 

You can read more about the browser API here. https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver

Additional to this, once you start having to parse a thing that looks like JavaScript from a string you get into the risky territory of CSP non-compliance where any JS on the Dom can be passed to run in JS.

**Comment by phuongnd08** [comment]
perhaps we can use a common set of events? Like click, focus, blur and require custom events (user defined events) to be explicitly make known (for example, via data-custom-events)

**Comment by dhh** [comment]
I don't see a path to this. We already have a params API as well. Doesn't appear better or easier to me either. Appreciate the time spent suggesting it none the less ✌️
