### ISSUE TITLE
Provide / Inject Feature

### ISSUE THREAD

**Issue by gseidel** [hotwired/stimulus#538]
First of all, thanks to the contributers for this light and easy to use library.

I try to use stimulus in my project, but having some problems to integrate it in a nice way and have a small feature request to solve it that it looks a bit nicer to me :)

The main problem is that I don't have control of creating a controller. Stimulus creates controllers "magically" for you. So I can't use my own objects, which I would normally pass within the constructor or via setter. I want this to forward my domain logic into my own classes and use the stimulus controllers more as an adaptor.

The workaround is to use prototyping.

```js
let myObject = new Foobar();
app.foobar = myObject;
app.register('my', MyController);
```

So inside the controller I have access to my object via `this.application.foobar`

I would like to see something more native in stimulus like they solve it in Vue.js with provide and inject.

```js
let myObject = new Foobar();
app.provide('foobar', myObject)
app.register('my', MyController);
```

```js
import { Controller } from "@hotwired/stimulus"

export default class extends Controller
{
    static injects = ['foobar'],

    clickAction() {
      this.foobar.doSomething();
    }
}
```

**Comment by dhh** [comment]
Stimulus registers controllers when they're spotted in the DOM. That's integral to the model. I don't think this way of manually provide object references is going to work. Because it wouldn't survive controllers getting removed and added back.

Think you might be better of having the stimulus controller emit an event when it connects, then have something catch and inject then.
