### ISSUE TITLE
Two connected Stimulus controllers after form submission with 422 response

### ISSUE THREAD

**Issue by janpeterka** [hotwired/stimulus#564]
I got stuck on problem with weird stimulus-controller button behavior to find out there are two connected Stimulus controllers.

I'm returning template "new" with 422 - Unprocessable entity, as suggested in documentation and here.
This leads me to situation where I have two connected controllers:
![Screenshot from 2022-07-19 22-19-01](https://user-images.githubusercontent.com/6343648/179841125-9b7a617d-3870-4934-b38c-27b56d55055e.png)
I first thought this is problem with cache, but even when cache is disabled, this is still happening.

I know this could be possibly solved with using redirect instead of 422, but I'm trying to avoid that.

Here is BE controller code, if thats interesting (using Flask + Jinja2):
```
 @route("update/<int:id>", methods=["POST"])
    def update(self, id):

       (...)

        form = TaskGroupForm(request.form, assignees=assignees)

        if not form.validate_on_submit():
            return (
                self.template("edit", id=id, form=form),
                422,
            )
```

Thanks for any ideas or advice!

**Comment by tleish** [comment]
Can you share the original HTML and the update response HTML?

**Comment by janpeterka** [comment]
Hi sorry for the delay. Here are the files.

[before.txt](https://github.com/hotwired/stimulus/files/9223247/before.txt)
[after.txt](https://github.com/hotwired/stimulus/files/9223246/after.txt)

**Comment by tleish** [comment]
Looking at the before/after... the recommended approach when using turbo is to place javascript inside the head, not body.  Because of turbo caching, putting javascript inside the body can cause behavior like this.

It used to be best practice to place large javascript at the end of the body so as to not block page rendering while the javascript was downloaded.  You can now place the javascript tags in the head and [use attributes defer or async](https://javascript.info/script-async-defer) to make the script loading non-blocking.


See also [Turbo Handbook > Understanding Caching](https://turbo.hotwired.dev/handbook/building#understanding-caching)

**Comment by janpeterka** [comment]
Well, that's the problem - as far as I'm concerned, I put stimulus to head - if you check second before.txt, stimulus is in head, but after redirect it is both in `head` and in `body` for some reason.
