### ISSUE TITLE
Why are there two packages in npmjs?

### ISSUE THREAD

**Issue by Eptagone** [hotwired/stimulus#594]
I see there is the main package [@hotwired/stimulus](https://www.npmjs.com/package/@hotwired/stimulus) but there is also the [simulus](https://www.npmjs.com/package/stimulus) package. What is it for?

**Comment by marcoroth** [comment]
Hey @Eptagone, the `stimulus` was the original one when the library first came out.

But once Hotwire was introduced the package name was changed to `@hotwired/stimulus` in order to streamline the branding with the other packages.

But since this was a breaking change and a bunch of third-party npm packages depended on the `stimulus` package we kept it around for a bit to smoothen the transition period.

**Comment by Eptagone** [comment]
Oh, I see.
Thanks for clarifying my doubt.
