### ISSUE TITLE
Targets not binding in template element

### ISSUE THREAD

**Issue by abuzzell** [hotwired/stimulus#682]
I'm finding that where I have a set of dom nodes with targets, plus an additional one inside an html content template element (`<template>`), the targets bind in all the normal elements, but not the one in the template. 

As a result, operations such as toggling a class on all the targets fails to toggle it on the one target inside the template.

Is there a way to do this?

**Comment by lb-** [comment]
Content inside the template element is not available for most DOM listeners, query selection and mutation observers. This is intentional and part of the HTML spec. 

See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/template

> While the parser does process the contents of the <template> element while loading the page, it does so only to ensure that those contents are valid; the element's contents are not rendered...

You will not be able to access any target elements from within template elements.

**Comment by abuzzell** [comment]
That's a shame, it would be nice to be able to adjust the template before using it. Closing, because it appears there is no stimulus workaround. I ended up manually messing about in querySelectorAll[data-$identifier-target][0].classList to accomplish this.
